config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Devise routes only sessions
  devise_for :admins, only: %i[sessions]

  resources :tasks do
    resources :scammers, only: %i[new create show]
  end
  root 'pages#home'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/scammer.rb
class Scammer < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
require "json"
require "open-uri"

class Task < ApplicationRecord
  has_many :scammers, dependent: :destroy
  accepts_nested_attributes_for :scammers, allow_destroy: true
  validates :cep, presence: true, length: { is: 8 }
  # Validate scam type with SCAM_TYPES
  # validates :scam_type, inclusion: { in: SCAM_TYPES }
  validate :valid_cep?
  # Scam types for select
  SCAM_TYPE = ["Whatsapp", "Site", "Email", "Instagram"]
  SCAM_TYPE_FOR_SEARCH = ["Tipo de golpe...", "Whatsapp", "Site", "Email", "Instagram"]

  # Parse url = "https://viacep.com.br/ws/json/" see response is true
  def valid_cep?
    if cep.empty?
      errors.add(:cep, "campo obrigatório")
    else
      url = "https://viacep.com.br/ws/#{cep}/json/"
      ceps = URI.open(url).read
      cepis = JSON.parse(ceps)
      errors.add(:cep, " inválido") unless cepis["erro"].blank?
    end
  end
end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Pages controller  -  This controller handles the pages of the application
class PagesController < ApplicationController
  def home
  end

  def reporting; end

  def types_of_fraud; end

  def prevention; end

  def about_us; end
end

app/controllers/scammers_controller.rb
class ScammersController < ApplicationController
  before_action :set_task, only: %i[show new create]

  def show
    @scammer = Scammer.find(params[:id])
  end

  def new
  end

  def create
  end

  private

  def scammer_params
    params.require(:scammer).permit(:name, :phone, :email, :description, :category, :task_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
require "json"
require "open-uri"

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :authenticate_admin!, only: %i[show destroy]

  # GET /tasks or /tasks.json
  def index
    respond_to do |format|
      format.html
      format.text { render partial: "tasks", locals: { tasks: Task.all }, formats: [:html] }
    end
    map
    # Search
    if params[:search].present? && params[:query].blank? && params[:zip].blank?
      @tasks = Task.where(scam_type: params[:search]).page(params[:page]).per(10)

    elsif params[:search].present? && params[:query].present? && params[:zip].blank?
      @tasks = Task.where(scam_type: params[:search]).where(date: params[:query]).page(params[:page]).per(10)

    elsif params[:search].present? && params[:query].blank? && params[:zip].present?
      @tasks = Task.where(scam_type: params[:search]).where(cep: params[:zip]).page(params[:page]).per(10)

    elsif params[:search].present? && params[:query].present? && params[:zip].present?
      @tasks = Task.where(scam_type: params[:search], date: params[:query],
                          cep: params[:zip]).page(params[:page]).per(10)

    elsif params[:query].present? && params[:search].blank? && params[:zip].blank?
      @tasks = Task.where(date: params[:query]).page(params[:page]).per(10)

    elsif params[:query].present? && params[:search].blank? && params[:zip].present?
      @tasks = Task.where(date: params[:query],
                          cep: params[:zip]).page(params[:page]).per(10).order("created_at DESC")

    elsif params[:zip].present? && params[:search].blank? && params[:query].blank?
      @tasks = Task.where(cep: params[:zip]).page(params[:page]).per(10).order("created_at DESC")

    else
      @tasks = Task.all.page(params[:page]).per(10).order("created_at DESC")
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @tasks = Task.all
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.scammers.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    # raise
    if @task.save && Zone.find_by(ddd: set_ddd).present?

      # Save nested form scammer data
      @scammer = Scammer.new(scammer_params[:scammer])
      @scammer.task_id = @task.id
      @scammer.save

      # Save count in ddd table
      Zone.find_by(ddd: set_ddd).increment!(:count_of_scammers)
      # end

      # Zone.create(task_id: @task.id, ddd: set_ddd, count: +1) not working, create a new row
      redirect_to tasks_path, flash: { success: "Obrigado por compartilhar sua experiência!" }
      #  flash.now[:alert] = "Task was successfully created."

    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    # Only for admins
    # respond_to do |format|
    #   if @task.update(task_params)
    #     format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #   end
    # end
  end

  def destroy
    # Only for admins
    # @scammer = Scammer.find(task_id: @task.id)
    # @task.scammer.destroy
    @task.destroy
    redirect_to tasks_url, notice: "Task was successfully destroyed."
  end

  # def set ddd by cep
  def set_ddd
    url = "https://viacep.com.br/ws/#{params[:task][:cep]}/json/"
    ddds = URI.open(url).read
    dddi = JSON.parse(ddds)
    hash = dddi.select { |ddd| ddd["ddd"] }
    @ddd = hash["ddd"].to_i
  end

  # Render the map

  def map
    @zones = Zone.where.not(latitude: nil, longitude: nil) # returns zones with coordinates
    # Mark a zone DDD in google maps
    @markers = @zones.map do |zone|
      {
        lat: zone.latitude,
        lng: zone.longitude,
        ddd: zone.ddd
      }
    end
    # Count total scamers
    @total_scammers = Zone.where.not(count_of_scammers: nil).sum(:count_of_scammers)

    # Count the number of scammers in each ddd
    @countOfScammer = Zone.where.not(count_of_scammers: 0)
    @countOfScammers = @countOfScammer.map do |zone|
      {
        ddd: zone.ddd,
        count_of_scammers: zone.count_of_scammers
      }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:date, :scam_type, :cep, :money_lost, :description)
  end

  def scammer_params
    params.require(:task).permit(scammer: %i[name phone email website description category])
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  def index
    @zones = Zone.where.not(latitude: nil, longitude: nil) # returns zones with coordinates
    # Mark a zone DDD in google maps
    @markers = @zones.map do |zone|
      {
        lat: zone.latitude,
        lng: zone.longitude,
        ddd: zone.ddd
      }
    end
    # Count total scamers
    @total_scammers = Zone.where.not(count_of_scammers: nil).sum(:count_of_scammers)

    # Count the number of scammers in each ddd
    @countOfScammer = Zone.where.not(count_of_scammers: 0)
    @countOfScammers = @countOfScammer.map do |zone|
      {
        ddd: zone.ddd,
        count_of_scammers: zone.count_of_scammers
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Device detection
  def device
    agent = request.user_agent
    return "tablet" if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    return "mobile" if agent =~ /Mobile/

    return "desktop"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PegaGolpista</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('fav_icon.svg') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GMAPS_API_KEY']}&&libraries=places", defer: true %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@800&family=Square+Peg&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="content" >
    <%= yield %>
    <%= turbo_frame_tag "remote_modal", target: "_top" %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%# navbar da home começa aqui %>
<nav class="navbar navbar-expand-sm sticky-top"
     data-controller="navbar"
     data-action="scroll@window->navbar#updateNavbar"
  >
  <div class="container d-flex justify-content-center">
    <a class="navbar-brand d-flex justify-content-center" href="/">
      <%= image_tag "logo.svg", class: "logo" %>
    </a>
  </div>
</nav>
<%# banner começa aqui %>
<div class="banner">
  <div class="container hero">
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.3);">
      <%# <button class="btn-banner"> %>
      <div class="container info">
        <h1>Ajude-nos a avisar outras pessoas!</h1>
        <p>O PegaGolpista é o site Nº 1 em <strong>rastreamento</strong>, <strong>denúncias</strong> e <strong>informações</strong> sobre os mais diferentes tipos de golpes.</p>
        <p class="p-xl">Caso queira fazer uma <strong>denúncia</strong> ou ver as denúncias publicadas, poderá encontrar o nosso formulário e as denúncias clicando nos botões abaixo.</p>
        <%# </button> %>
      </div>
    </div>
    <div class="container buttons">
      <div class="row d-flex justify-content-center">
        <a href="tasks/new" class="btn-denunciar">DENUNCIAR</a>
        <a href="tasks" class="btn-lista">VER DENÚNCIAS</a>
      </div>
    </div>
  </div>
</div>

app/views/pages/map.html.erb
<div class="containner mt-5">
  <div class="row">
    <div class="col-lg-2" ></div>
    <div class="col-12 col-lg-6 col-md-12">
      <div class="map">
        <%# initialize Google Map %>
        <div data-controller="maps" data-action="load@window->maps#initializeMap" id="map" style="width: 100%; height: 500px;"></div>
      </div>
    </div>
    <%# section search bar maps start %>
    <div class="col-lg-2" >
      <div class="search-for-scammers">
        <div class="card-1 card text-white h-100">
          <div class="card-body d-flex flex-column align-items-start">
            <h4 class="card-title text-center">Procure por golpistas</h4>
            <div class="input-group">
              <input type="number" class="form-control" placeholder="CEP" aria-label="Recipient's cep" aria-describedby="button-addon2">
            </div>
            <div class="input-group mt-2">
              <input type="text" class="form-control" placeholder="Scammer Name" aria-label="Recipient's username" aria-describedby="button-addon2">
            </div>
            <div class="input-group mt-2">
              <input type="text" class="form-control" placeholder="Scammer Type" aria-label="Recipient's username" aria-describedby="button-addon2">
            </div>
            <div class="input-group mt-2">
              <input type="text" class="form-control" placeholder="Phone" aria-label="Recipient's phone" aria-describedby="button-addon2">
            </div>
            <div class="input-group mt-2">
              <input type="text" class="form-control" placeholder="e-mail" aria-label="Recipient's email" aria-describedby="button-addon2">
            </div>
            <p class="card-text banner-text mt-2">*Insira ao menos um dos campos e realize sua busca</p>
            <a href="#" class="btn-1 btn btn-danger w-100 text-white  mt-auto">BUSCAR</a>
          </div>
        </div>
      </div>
    </div>
  </div>

<%#
<div class="containner mt-5">
  <div class="row">
    <div class="col-lg-2" ></div>
    <div class="col-12 col-lg-6 col-md-12">
      <div class="map" >
        <div class="mapouter">
          <div class="gmap_canvas">
            <iframe width="100%" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=rio%20de%20janeiro%20brasil&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
            <a href="https://www.embedgooglemap.net/blog/divi-discount-code-elegant-themes-coupon/"></a>
          </div>
          <style>
            .mapouter{position:relative;text-align:right;height:500px;width:100%;}
            .gmap_canvas {overflow:hidden;background:none!important;height:500px;width:100%;}
          </style>
        </div>
      </div>
    </div> %>

app/views/scammers/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender", style="display: none;" data-remote-modal-target="modal">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/scammers/_scammer.html.erb
<%# <% Email replace method %>
<% def replace_email(email) %>
<%  if email.split('@')[0].length <= 5 %>
  <%    email.gsub(/(?<=.{1}).(?=[^@]*?@)/, '*') %>
<% else %>
  <%   email.gsub(/(?<=.{4}).(?=.*@)/, '*')%>
<% end %>
<% end %>
<%# <% Phone replace method %>
<% def replace_phone(phone) %>
<%   phone.gsub(/(?<=.{2}).(?=.{4})/, '*') %>
<% end %>
<%# Show scammers details %>
<div id="<%= dom_id @scammer %>">
  <p>
    <strong>Nome usado pelo golpista:</strong>
    <%= @scammer.name %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= replace_email(@scammer.email) %>
  </p>
  <p>
    <strong>Telefone:</strong>
    <%= replace_phone(@scammer.phone) %>
  </p>
  <p>
    <strong>Website:</strong>
    <%= @scammer.website %>
  </p>
  <p>
    <strong>Descrição:</strong>
    <%= @scammer.description %>
  </p>
</div>

app/views/scammers/show.html.erb
<%= render "remote_modal", title: "Detalhes do Golpe" do %>

  <%= render @scammer %>

<% end %>

app/views/shared/_banner.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="banner">
        <div class="container hero">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.4)">
                <%# <button class="btn-banner"> %>
                <div class="container info">
                  <h1 class="h1">Ajude-nos a avisar outras pessoas!</h1>
                  <p class="display-1">O PegaGolpista é o site Nº 1 em <strong>rastreamento</strong>, <strong>denúncias</strong> e <strong>informações</strong> sobre os mais diferentes tipos de golpes.</p>
                  <p class="display-1">Caso queira fazer uma <strong>denúncia</strong> ou ver as denúncias publicadas, poderá encontrar o nosso formulário e as denúncias clicando nos botões abaixo.</p>
                  <%# </button> %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="container buttons">
            <div class="row d-flex justify-content-center">
              <a href="tasks/new" class="btn-denunciar">DENUNCIAR</a>
              <a href="tasks" class="btn-lista">VER DENÚNCIAS</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-background">
  <div class="footer">
    <div class="footer-links">
      <a href="https://c.tenor.com/_4YgA77ExHEAAAAd/rick-roll.gif"><i class="fab fa-twitter"></i></a>
      <a href="https://i2-prod.walesonline.co.uk/incoming/article1876018.ece/ALTERNATES/s615/13212051.jpg"><i class="fab fa-instagram"></i></a>
    </div>
    <div class="footer-copyright">
      <h3 class="d-flex justify-content-center"><strong>© 2022 PegaGolpista.</strong></h3>
      <h3 class="d-flex justify-content-center">Todos os direitos reservados.</h3>
      <ul class="list-inline">
        <li class="privacidade p-1">Privacidade</li>
        <li class="faq p-1">Perguntas Frequentes</li>
        <li class="ajuda p-1">Ajuda</li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top"
 data-controller="navbar"
     data-action="scroll@window->navbar#updateNavbar">
  <div class="container nav">
    <a class="navbar-brand" href="/">
      <%= image_tag "logo.svg", alt: "logo", class: "logo" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "DENUNCIAR", "../tasks/new", class: "nav-link denunciar" %>
        </li>
        <li class="nav-item">
          <%= link_to "VER DENÚNCIAS", "../tasks", class: "nav-link ver" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<div style="min-height: 74.2vh">
  <div class="container rounded-4 mb-5"  id="form-container">
    <div data-controller="form" class="p-5">
      <div class="text-center mb-5" style="color: white">
        <h4>CADASTRE UMA NOVA DENÚNCIA</h4>
      </div>
      <%= simple_form_for(@task) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs text-start">
          <%# Disable date input %>
          <%# <%= f.input :date, as: :date, label: "Data", input_html: { value: Date.today }, disabled: true %>
          <div class="form-data">
            <%= f.input :date, required: false, as: :date, order: [:day, :month, :year], label: "DATA DO GOLPE", input_html: { value: Date} %>
          </div>
          <% select_options = Task::SCAM_TYPE %>
          <%= f.input :scam_type, required: false, collection: select_options, label: "TIPO DE GOLPE", input_html: { class: "form-select" } %>
          <%= f.input :cep, required: false, label: "SEU CEP" %>
          <div class="d-flex justify-content-between">
            <div class="form-actions" 
                 style="box-shadow: rgba(0, 0, 0, 0.17) 0px -23px 25px 0px inset, rgba(0, 0, 0, 0.15) 0px -36px 30px 0px inset, rgba(0, 0, 0, 0.1) 0px -79px 40px 0px inset, rgba(0, 0, 0, 0.06) 0px 2px 1px, rgba(0, 0, 0, 0.09) 0px 4px 2px, rgba(0, 0, 0, 0.09) 0px 8px 4px, rgba(0, 0, 0, 0.09) 0px 16px 8px, rgba(0, 0, 0, 0.09) 0px 32px 16px;"
              >
              <%= f.button :submit, value:"Denunciar", class:"btn btn-danger" %>
            </div>
            <div class="btn btn-link" style="color: white" data-action="click->form#myFunction" >
              Acrescentar mais detalhes </div>
          </div>
        </div>
        <%# Simple fields for :scammer %>
        <div class="container-extra mt-2">
          <div class="form-inputs" id="form-toggle">
            <%= f.input :money_lost, label: "Quantia perdida" %>
            <%= f.simple_fields_for :scammer do |scammer| %>
              <%= scammer.input :name, required: false, label: "Nome usado pelo golpista" %>
              <%= scammer.input :email, required: false, label: "Email usado pelo golpista" %>
              <%= scammer.input :phone, required: false, label: "Telefone usado pelo golpista" %>
              <%= scammer.input :website, required: false, label: "Site ou plataforma onde ocorreu golpe" %>
              <%= scammer.input :description, required: false, label: "Descrição do golpe" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_search.html.erb
<div class="container search">
  <div class="search-form">
    <h2 class="search-h2-mobile">PROCURAR</h2>
    <%= form_tag tasks_path, method: :get, data: { turbo_frame: "search-results", turbo_action: "advance", controller: "search", action: "input->search#submit" }, class: "d-md-block d-lg-flex"  do %>
      <%= select_tag :search, options_for_select(Task::SCAM_TYPE, params[:search]), class: "form-select", id: "advanced-search-input"%>
      <%= text_field_tag :zip, params[:zip],class: "form-control",placeholder: "CEP" %>
      <%# If width mobile change date_filed %>
      <% if device == "mobile" || device == "tablet"%>
        <%= text_field_tag :query, params[:query],class: "form-control",placeholder: Time.now.strftime("%d/%m/%Y") %>
      <% else %>
        <%= date_field_tag :query, params[:query],class: "form-control",placeholder: Time.now.strftime("%d/%m/%Y") %>
      <% end %>
      <%= button_tag(type: "submit", class: "btn btn-primary search", data: {
        action: "submit->tasks#update",
      }) do %>
        <i class="fa fa-search"></i>
      <% end %>
      <%= link_to tasks_path, class: "btn btn-secondary reset" do %>
        <i class="fa fa-times"></i>
      <% end %>
    <% end %>
  </div>
  <div style="margin-bottom: 5vh" data-tasks-target="table">
    <%= turbo_frame_tag "search-results" do %>
      <%= render partial: "table", locals: { tasks: @tasks } %>
    <% end %>
  </div>
</div>

app/views/tasks/_table.html.erb
<% if @tasks.empty? %>
  <% # Align the text to the center %>
  <div class="text-center m-5">
    <h3 class="text-center"style="color: red">Nenhuma denúncia encontrada</h3>
    <h4 class="text-primary mb-3">Por favor refaça sua busca</h4>
    <% #path to go back indexex %>
    <%= link_to "Voltar", tasks_path, class: "btn btn-primary" %>
  </div>
  <div style="height: 30vh"></div>
<% else %>
  <div class="table-responsive">
    <table class="table mt-4">
      <thead class="bg-primary text-white">
        <tr>
          <th class="text-center align-middle" scope="col">Data</th>
          <th class="text-center align-middle" scope="col">Tipo de Golpe</th>
          <th class="text-center align-middle" scope="col">CEP</th>
          <th class="text-center align-middle" scope="col">Dinheiro Perdido</th>
          <th class="text-center align-middle" scope="col">Detalhes</th>
          <% if admin_signed_in? %>
            <th scope="col">Deletar</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <%# Parse date i18n %>
            <td class="text-center align-middle" ><%= l task.created_at, format: "%d/%m/%Y" %></td>
            <td class="text-center align-middle" ><%= task.scam_type %></td>
            <%# Regex hidden last 3 digits cep %>
            <td class="text-center align-middle" ><%= task.cep.to_s.gsub(/(\d{5})(\d{3})/, '\1-***') %></td>
            <% # Check money lost is nill %>
            <%   if task.money_lost.nil? %>
              <td class="text-center align-middle" ><%= "Não informado" %></td>
            <% else %>
              <td class="text-center align-middle" ><%= number_to_currency task.money_lost %></td>
            <% end %>
            <% # Check Scammer is empty %>
            <% if task.scammers.pluck(:name, :phone, :email, :website).flatten.delete_if(&:empty?).empty? %>
              <td class="text-center align-middle" >N/A</td>
            <% else %>
              <td class="text-center align-middle" >
                <%= link_to "Ver", task_scammer_path(task_id: task, id:task.scammers.first.id), data: { turbo_frame: "remote_modal" }%>
              </td>
            <% end %>
            <% # If user Show button to redirect to task %>
            <% if admin_signed_in? %>
              <td class="text-center align-middle" >
                <% # Link to delete task %>
                <%= button_to "Deletar", task_path(task), method: :delete, data: { confirm: "Tem certeza?" } %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <% # Paginate %>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="paginate d-flex justify-content-center" style="margin-top: 5%">
            <div class="paginate-mobile">
              <% if @tasks.current_page > 1 %>
                <%= link_to "Anterior", tasks_path(page: @tasks.current_page - 1), class: "btn btn-primary mr-1" %>
                <%= link_to "Próxima", tasks_path(page: @tasks.current_page + 1), class: "btn btn-primary mr-1" %>
              <% elsif @tasks.current_page > 0 %>
                <%= link_to "Próxima", tasks_path(page: @tasks.current_page + 1), class: "btn btn-primary mr-1" %>
              <% end %>
            </div>
            <%= paginate @tasks, theme: 'bootstrap-5' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<%= render 'shared/navbar' %>
<div class="container todo-index">
  <div data-controller="tasks" >
    <div class="d-flex justify-content-between" style="margin-top: 3vh;">
      <h2 class="display-sm">Mapa de <span style="color: red;">Denúncias</span></h2>
      <h3 class="denuncias">Denúncias <span>Registradas:</span> <span style="color: red;"><%= @total_scammers %></span></h3>
    </div>
    <div class='row'>
      <div >
        <%= render partial: "zones/map" %>
      </div>
    </div>
    <div class="d-flex justify-content-center" style="margin-top: 5vh">
      <%= render partial: "search" %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render 'shared/navbar' %>


<%= render "form", task: @task %>

<%# <div> %>
  <%# link_to "Ir para Denúncias", tasks_path %>
<%# </div> %>

app/views/tasks/show.html.erb
<div>
  <table class="table">
    <thead class="bg-primary text-white">
      <tr>
        <th scope="col">Data</th>
        <th scope="col">Tipo de Golpe</th>
        <th scope="col">CEP</th>
        <th scope="col">Dinheiro Perdido</th>
        <th scope="col">Detalhes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <%# Parse date i18n %>
        <td><%= @task.created_at %></td>
        <td><%= @task.scam_type %></td>
        <%# Regex hidden last 3 digits cep %>
        <td><%= @task.cep.to_s.gsub(/(\d{5})(\d{3})/, '\1-***') %></td>
        <% # Check money lost is nill %>
        <%   if @task.money_lost.nil? %>
          <td><%= "Não informado" %></td>
        <% else %>
          <td><%= @task.money_lost %></td>
        <% end %>
        <td>
          <% # Link to delete task %>
          <%= button_to "Deletar", task_path(@task), method: :delete, data: { confirm: "Tem certeza?" } %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/zones/_map.html.erb
<%# initialize Google Map %>
<div data-controller="maps" data-maps-markers-value="<%= @markers.to_json %>" data-maps-count-of-scammers-value="<%= @countOfScammers.to_json %>" id="map" style="width: 100%; height: 500px;"></div>

app/views/zones/index.html.erb
<%= render 'shared/navbar' %>
<%# Render zones map %>

<%= render partial: "zones/map" %>
<%# Section map end %>